
name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Git init 
        run: |
          git config --global user.email xxx.com
          git config --global user.name robot

      - name: Soluation1
        run: |
          python bSpider.py 6 4 BV1734y117nR
          for i in `find ./main/ -size +100M`;do 
          git lfs track "$i" ;
          git add $i;
          git commit -m "update{{1}}" -a
          git push
          done 
          git add main context.json pic.png
          du -ah
      - name: Commit and Push 1
        run: |
          git commit -m "update1" -a
          git push
      - name: Soluation2
        run: |
          python bSpider.py 6 5 BV1734y117nR
          for i in `find ./main/ -size +100M`;do 
          git lfs track "$i" ;
          git add $i;
          git commit -m "update{{1}}" -a
          git push
          done 
          git add main context.json pic.png
      - name: Commit and Push 2
        run: |
          git commit -m "update2" -a
          git push
    
